tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface-bright": "#f7f9fb",
                "secondary-fixed": "#85f8c4",
                "on-surface": "#191c1e",
                "on-error": "#ffffff",
                "on-primary-fixed": "#131b2e",
                "tertiary-container": "#271901",
                "on-primary": "#ffffff",
                "inverse-primary": "#bec6e0",
                "outline-variant": "#c6c6cd",
                "on-secondary": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "error-container": "#ffdad6",
                "secondary-fixed-dim": "#68dba9",
                "on-surface-variant": "#45464d",
                "on-background": "#191c1e",
                "on-secondary-fixed": "#002114",
                "primary-fixed": "#dae2fd",
                "surface-tint": "#565e74",
                "outline": "#76777d",
                "on-error-container": "#93000a",
                "on-secondary-container": "#00714e",
                "secondary-container": "#82f5c1",
                "surface-container-low": "#f2f4f6",
                "surface-container-highest": "#e0e3e5",
                "tertiary-fixed": "#fcdeb5",
                "error": "#ba1a1a",
                "primary-fixed-dim": "#bec6e0",
                "on-tertiary-fixed-variant": "#574425",
                "on-tertiary-fixed": "#271901",
                "tertiary": "#000000",
                "inverse-on-surface": "#eff1f3",
                "primary-container": "#131b2e",
                "on-secondary-fixed-variant": "#005137",
                "secondary": "#006c4a",
                "on-tertiary-container": "#98805d",
                "surface": "#f7f9fb",
                "on-tertiary": "#ffffff",
                "surface-container-high": "#e6e8ea",
                "on-primary-fixed-variant": "#3f465c",
                "on-primary-container": "#7c839b",
                "inverse-surface": "#2d3133",
                "surface-variant": "#e0e3e5",
                "surface-container": "#eceef0",
                "tertiary-fixed-dim": "#dec29a",
                "primary": "#000000",
                "surface-dim": "#d8dadc",
                "background": "#f7f9fb"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "stack-md": "1rem",
                "stack-sm": "0.5rem",
                "gutter": "1.5rem",
                "stack-lg": "2rem",
                "sidebar-width": "80px",
                "container-padding": "2rem"
            },
            "fontFamily": {
                "headline-md": ["Hanken Grotesk"],
                "body-md": ["Hanken Grotesk"],
                "data-mono": ["JetBrains Mono"],
                "headline-sm": ["Hanken Grotesk"],
                "body-lg": ["Hanken Grotesk"],
                "label-md": ["Hanken Grotesk"],
                "headline-lg": ["Hanken Grotesk"]
            },
            "fontSize": {
                "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "data-mono": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
                "headline-sm": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
                "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
                "headline-lg": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
            }
        },
    },
}
